"""TCB<->TDB parameter tables extracted from PINT.

DO NOT EDIT -- regenerate with ``python tools/regen_tcb_tables.py``.

Restricted to parameters JaxPINT declares.  The conversion logic that consumes
these lives in :mod:`jaxpint.par._tcb_tables`.
"""

from __future__ import annotations

# name -> effective dimensionality n; the scale factor is ``IFTE_K ** -n``
# (PINT: ``scale_parameter(model, par, -effective_dimensionality, ...)``).
SCALE_DIMENSIONALITY: dict[str, int] = {
    "A0": 1,
    "A1": 1,
    "A1DOT": 0,
    "A1X_0000": 1,
    "B0": 1,
    "CMWXCOS_0001": 1,
    "CMWXFREQ_0001": -1,
    "CMWXSIN_0001": 1,
    "DECJ": 0,
    "DM": -1,
    "DM1": -2,
    "DMWXCOS_0001": -1,
    "DMWXFREQ_0001": -1,
    "DMWXSIN_0001": -1,
    "DMX_0001": -1,
    "DR": 0,
    "DTH": 0,
    "ECC": 0,
    "EDOT": -1,
    "ELAT": 0,
    "ELONG": 0,
    "EPS1": 0,
    "EPS1DOT": -1,
    "EPS2": 0,
    "EPS2DOT": -1,
    "EXPDIPAMP_1": 1,
    "EXPDIPEPS": 1,
    "EXPDIPFREF": -1,
    "EXPDIPIDX_1": 0,
    "EXPDIPTAU_1": 1,
    "F0": -1,
    "FB0": -1,
    "GAMMA": 1,
    "GLF0D_1": -1,
    "GLF0_1": -1,
    "GLF1_1": -2,
    "GLF2_1": -3,
    "GLPH_1": 0,
    "GLTD_1": 1,
    "H3": 1,
    "H4": 1,
    "JUMP1": 1,
    "KIN": 0,
    "KOM": 0,
    "LNEDOT": -1,
    "M2": 1,
    "MTOT": 1,
    "NE_SW": -2,
    "NE_SW1": -3,
    "OM": 0,
    "OMDOT": -1,
    "PB": 1,
    "PBDOT": 0,
    "PHOFF": 0,
    "PMDEC": -1,
    "PMELAT": -1,
    "PMELONG": -1,
    "PMRA": -1,
    "PWF0_1": -1,
    "PWF1_1": -2,
    "PWF2_1": -3,
    "PWPH_1": 0,
    "PX": -1,
    "RAJ": 0,
    "RNAMP": 0,
    "RNIDX": 0,
    "SHAPMAX": 0,
    "SINI": 0,
    "STIGMA": 0,
    "SWP": 0,
    "SWXDM_0001": -1,
    "SWXP_0001": 0,
    "T0X_0000": 1,
    "TNCHROMAMP": 0,
    "TNCHROMGAM": 0,
    "TNCHROMTSPAN": 1,
    "TNDMAMP": 0,
    "TNDMGAM": 0,
    "TNDMTSPAN": 1,
    "TNREDAMP": 0,
    "TNREDTSPAN": 1,
    "TNSWAMP": 0,
    "TNSWGAM": 0,
    "WXCOS_0001": 1,
    "WXFREQ_0001": -1,
    "WXSIN_0001": 1,
    "XOMDOT": -1,
    "XPBDOT": 0,
}

# Epochs: t_tdb = (t_tcb - IFTE_MJD0) / IFTE_K + IFTE_MJD0
MJD_PARAMS: frozenset[str] = frozenset(
    {
        "CMWXEPOCH",
        "DMEPOCH",
        "DMWXEPOCH",
        "DMXR1_0001",
        "DMXR2_0001",
        "EXPDIPEP_1",
        "GLEP_1",
        "PEPOCH",
        "POSEPOCH",
        "PWEP_1",
        "PWSTART_1",
        "PWSTOP_1",
        "SWEPOCH",
        "SWXR1_0001",
        "SWXR2_0001",
        "T0",
        "TASC",
        "WXEPOCH",
        "XR1_0000",
        "XR2_0000",
    }
)

# PINT sets convert_tcb2tdb=False for these and leaves them untouched.
NOT_CONVERTIBLE: frozenset[str] = frozenset(
    {
        "BINARY",
        "CHI2",
        "CHI2R",
        "CLOCK",
        "CM",
        "CM1",
        "CMEPOCH",
        "CMXR1_0001",
        "CMXR2_0001",
        "CMX_0001",
        "CORRECT_TROPOSPHERE",
        "DILATEFREQ",
        "DMDATA",
        "DMEFAC1",
        "DMEQUAD1",
        "DMJUMP1",
        "DMRES",
        "ECL",
        "ECORR1",
        "EFAC1",
        "EPHEM",
        "EQUAD1",
        "FD1",
        "FD10JUMP1",
        "FD11JUMP1",
        "FD12JUMP1",
        "FD13JUMP1",
        "FD14JUMP1",
        "FD15JUMP1",
        "FD16JUMP1",
        "FD17JUMP1",
        "FD18JUMP1",
        "FD19JUMP1",
        "FD1JUMP1",
        "FD20JUMP1",
        "FD2JUMP1",
        "FD3JUMP1",
        "FD4JUMP1",
        "FD5JUMP1",
        "FD6JUMP1",
        "FD7JUMP1",
        "FD8JUMP1",
        "FD9JUMP1",
        "FDJUMPLOG",
        "FINISH",
        "IFUNC1",
        "INFO",
        "K96",
        "NHARMS",
        "NTOA",
        "PLANET_SHAPIRO",
        "PSR",
        "RM",
        "SIFUNC",
        "START",
        "SWM",
        "T2CMETHOD",
        "TIMEEPH",
        "TNCHROMC",
        "TNCHROMIDX",
        "TNDMC",
        "TNEQ1",
        "TNREDC",
        "TNREDGAM",
        "TNSWC",
        "TRACK",
        "TRES",
        "TZRFRQ",
        "TZRMJD",
        "TZRSITE",
        "UNITS",
        "WAVE1",
        "WAVEEPOCH",
        "WAVE_OM",
    }
)
