"""JaxPINT: JAX-accelerated pulsar timing (port of PINT)."""

import jax as _jax

_jax.config.update("jax_enable_x64", True)

from .dual_float import DualFloat
from .types import TOAData, ParameterVector
from .components import PhaseComponent, DelayComponent, NoiseComponent
from .phase import Spindown, Glitch, IFunc, PhaseJump, PiecewiseSpindown, Wave
from .delay import (
    AstrometryEcliptic,
    AstrometryEquatorial,
    CMWaveX,
    ChromaticCM,
    ChromaticCMX,
    DMWaveX,
    DispersionDM,
    DispersionDMX,
    ExponentialDip,
    FDJump,
    FrequencyDependent,
    SolarSystemShapiroDelay,
    SolarWindDispersion,
    SolarWindDispersionX,
    TroposphereDelay,
    WaveX,
)
from .binary import (
    BinaryBT,
    BinaryBTPiecewise,
    BinaryDD,
    BinaryDDGR,
    BinaryDDK,
    BinaryELL1,
    solve_kepler,
)
from .noise import (
    EcorrNoise,
    NoiseModel,
    PLChromNoise,
    PLDMNoise,
    PLRedNoise,
    PLSWNoise,
    ScaleToaError,
)
from .model import TimingModel
from .fitters import (
    GLSFitResult,
    GLSFitter,
    WidebandGLSFitResult,
    WidebandGLSFitter,
    WLSFitResult,
    WLSFitter,
    compute_design_matrix,
    compute_dm_residuals,
    compute_phase_residuals,
    compute_time_residuals,
    compute_wideband_design_matrix,
    compute_wideband_residuals,
)
from .bridge import (
    build_timing_model,
    extract_tzr_toa,
    params_to_pint_model,
    pint_model_to_params,
    pint_toas_to_jax,
)
from .likelihood import single_pulsar_logL
from .loaders import NanogravPTA, load_nanograv_pta
from .simulation import apply_delay_to_toas, make_fake_toas, simulate_noise, zero_residuals
from .utils import (
    fourier_sum,
    normalize_designmatrix,
    sherman_morrison_dot,
    taylor_horner,
    taylor_horner_deriv,
    taylor_horner_phase,
    weighted_mean,
    weighted_mean_sdev,
    woodbury_dot,
    woodbury_solve,
)

__all__ = [
    "AstrometryEcliptic",
    "AstrometryEquatorial",
    "BinaryBT",
    "BinaryBTPiecewise",
    "BinaryDD",
    "BinaryDDGR",
    "BinaryDDK",
    "BinaryELL1",
    "CMWaveX",
    "ChromaticCM",
    "ChromaticCMX",
    "DMWaveX",
    "DelayComponent",
    "DispersionDM",
    "DispersionDMX",
    "EcorrNoise",
    "ExponentialDip",
    "FDJump",
    "FrequencyDependent",
    "GLSFitResult",
    "GLSFitter",
    "Glitch",
    "IFunc",
    "NanogravPTA",
    "NoiseComponent",
    "NoiseModel",
    "PLChromNoise",
    "PLDMNoise",
    "PLRedNoise",
    "PLSWNoise",
    "DualFloat",
    "ParameterVector",
    "PhaseComponent",
    "PhaseJump",
    "PiecewiseSpindown",
    "ScaleToaError",
    "SolarSystemShapiroDelay",
    "SolarWindDispersion",
    "SolarWindDispersionX",
    "single_pulsar_logL",
    "Spindown",
    "TOAData",
    "TimingModel",
    "TroposphereDelay",
    "Wave",
    "WaveX",
    "WidebandGLSFitResult",
    "WidebandGLSFitter",
    "WLSFitResult",
    "WLSFitter",
    "apply_delay_to_toas",
    "build_timing_model",
    "compute_design_matrix",
    "compute_dm_residuals",
    "compute_phase_residuals",
    "compute_time_residuals",
    "compute_wideband_design_matrix",
    "compute_wideband_residuals",
    "extract_tzr_toa",
    "fourier_sum",
    "load_nanograv_pta",
    "make_fake_toas",
    "normalize_designmatrix",
    "params_to_pint_model",
    "pint_model_to_params",
    "pint_toas_to_jax",
    "sherman_morrison_dot",
    "simulate_noise",
    "solve_kepler",
    "taylor_horner",
    "taylor_horner_deriv",
    "taylor_horner_phase",
    "weighted_mean",
    "weighted_mean_sdev",
    "woodbury_dot",
    "woodbury_solve",
    "zero_residuals",
]
