#!/usr/bin/env python
"""Dev/release tool (NOT shipped) for the JaxPINT clock subsystem.

Two jobs, both run occasionally by a maintainer:

* ``--metadata`` (default): regenerate ``jaxpint/data/clock/clock_metadata.json``
  -- the committed read-schema -- from PINT's ``observatories.json`` + the BIPM
  rule. Needs PINT installed but **no network**.
* ``--bump-ref``: fetch the IPTA ``main`` HEAD SHA+date (GitHub API) and rewrite
  ``jaxpint/clock/_pinned.py``. Needs network.

This is the only place PINT is touched. Usage::

    python tools/bump_clock_pin.py            # regenerate metadata
    python tools/bump_clock_pin.py --bump-ref # also bump the seed pin
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
_META = _REPO / "jaxpint" / "data" / "clock" / "clock_metadata.json"
_PINNED = _REPO / "jaxpint" / "clock" / "_pinned.py"

_FORMAT_BY_EXT = {".dat": "tempo", ".clk": "tempo2"}


def _normalise_clock_file(value):
    """Return a list of (name, valid_beyond_ends) from a clock_file field."""
    if not value:
        return []
    if isinstance(value, (str, dict)):
        value = [value]
    out = []
    for item in value:
        if isinstance(item, dict):
            out.append((item["name"], bool(item.get("valid_beyond_ends", False))))
        else:
            out.append((item, False))
    return out


def _fmt_for(name: str, declared: str | None) -> str:
    if declared:
        return declared
    return _FORMAT_BY_EXT.get(Path(name).suffix, "tempo2")


def generate_metadata() -> dict:
    import pint  # noqa: F401
    import pint.observatory.special_locations  # noqa: F401  registers bary/geo
    import pint.observatory.topo_obs  # noqa: F401  registers ground stations
    from pint.config import runtimefile
    from pint.observatory import Observatory, bipm_default, get_observatory

    # The raw DB carries per-file flags (clock_fmt, bogus_last_correction,
    # valid_beyond_ends) that aren't exposed on the live objects; the registry
    # carries the resolution keys + timescale.  Use both.
    obs_db = json.loads(Path(runtimefile("observatories.json")).read_text())

    files: dict[str, dict] = {}
    observatories: dict[str, dict] = {}

    bipm_bogus_through = "bipm2019"
    default_bipm = str(bipm_default)

    for name in sorted(Observatory.names_and_aliases().keys()
                       if hasattr(Observatory, "names_and_aliases")
                       else Observatory._registry.keys()):
        try:
            obs = get_observatory(name)
        except Exception:
            continue
        # Canonicalise on the object's own name (aliases resolve to the same obj).
        canonical = obs.name
        if canonical in observatories:
            continue

        entry = obs_db.get(canonical, {})
        clock_files = _normalise_clock_file(
            getattr(obs, "clock_files", None) or entry.get("clock_file")
        )
        declared_fmt = entry.get("clock_fmt") or getattr(obs, "clock_fmt", None)
        bogus = bool(entry.get("bogus_last_correction", False))

        observatories[canonical] = {
            "clock_file": [fn for fn, _ in clock_files],
            "apply_gps2utc": bool(getattr(obs, "apply_gps2utc", True)),
            "timescale": str(getattr(obs, "timescale", "utc")).lower(),
            "aliases": [str(a).lower() for a in (getattr(obs, "aliases", None) or [])],
            "tempo_code": (str(entry["tempo_code"]).lower()
                           if entry.get("tempo_code") else None),
            "itoa_code": (str(entry["itoa_code"]).lower()
                          if entry.get("itoa_code") else None),
        }
        for fn, vbe in clock_files:
            files.setdefault(
                fn,
                {
                    "format": _fmt_for(fn, declared_fmt),
                    "bogus_last_correction": bogus,
                    "valid_beyond_ends": vbe,
                },
            )

    # Global correction files referenced by the chain by name.
    files.setdefault(
        "gps2utc.clk",
        {"format": "tempo2", "bogus_last_correction": False, "valid_beyond_ends": False},
    )
    files.setdefault(
        f"tai2tt_{default_bipm.lower()}.clk",
        {
            "format": "tempo2",
            "bogus_last_correction": default_bipm.lower() <= bipm_bogus_through,
            "valid_beyond_ends": False,
        },
    )

    return {
        "_comment": "Generated by tools/bump_clock_pin.py from PINT. Schema only; "
        "the bulk .clk/.dat are downloaded at runtime.",
        "format_by_extension": _FORMAT_BY_EXT,
        "default_bipm": default_bipm,
        # tai2tt_bipm<=2019 files carry a bogus far-future last correction.
        "bipm_bogus_through": bipm_bogus_through,
        "files": dict(sorted(files.items())),
        "observatories": dict(sorted(observatories.items())),
    }


def bump_ref() -> tuple[str, str]:
    from jaxpint.clock.fetch import resolve_latest_sha

    sha, date = resolve_latest_sha()
    text = _PINNED.read_text()
    text = re.sub(r'SEED_CLOCK_REF = "[^"]*"', f'SEED_CLOCK_REF = "{sha}"', text)
    text = re.sub(r'SEED_CLOCK_DATE = "[^"]*"', f'SEED_CLOCK_DATE = "{date}"', text)
    _PINNED.write_text(text)
    return sha, date


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--bump-ref", action="store_true", help="also bump the seed pin")
    args = ap.parse_args()

    meta = generate_metadata()
    _META.parent.mkdir(parents=True, exist_ok=True)
    _META.write_text(json.dumps(meta, indent=2) + "\n")
    print(f"wrote {_META} ({len(meta['files'])} files, "
          f"{len(meta['observatories'])} observatories, default {meta['default_bipm']})")

    if args.bump_ref:
        sha, date = bump_ref()
        print(f"bumped SEED_CLOCK_REF -> {sha} ({date})")


if __name__ == "__main__":
    main()
